on:
  schedule:
    - cron: '0 12 * * TUE'
name: Update Discovery Generated Types
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 16
      # Install all deps, including dev dependencies.
      - run: npm install
      # Generate types
      - run: npm run types
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6.0.5
        with: 
          base: main
          branch: update-discovery/patch
          add-paths: src/types.d.ts
          commit-message: "chore: update types from Discovery"
          title: "chore: update types from Discovery"
          body: |
            Automated pull-request to keep BigQuery Discovery types up-to-date.
      
