on:
  schedule:
    - cron: '0 12 * * TUE'
  pull_request:
name: Update Discovery Generated Types
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      # Install all deps, including dev dependencies.
      - run: npm install
      # Generate types
      - run: npm run types
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with: 
          base: main
          branch: update-discovery/patch
          add-paths: src/types.d.ts
          commit-message: "chore: update types from Discovery"
          title: "chore: update types from Discovery"
          body: |
            Automated pull-request to keep BigQuery Discovery types up-to-date.
      
